issueless/issue/__init__.py
from flask import Blueprint

bp = Blueprint('issue', __name__, url_prefix='/projects/<int:id>/issues')

from issueless.issue import views

issueless/issue/views.py
from time import time

from flask import (
    abort,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import current_user, login_required
from werkzeug.utils import secure_filename

from issueless.decorators import (
    access_issue_permission_required,
    assign_issue_permission_required,
    close_issue_permission_required,
    comment_and_upload_permission_required,
    delete_comment_permission_required,
    delete_file_permission_required,
    delete_issue_permission_required,
    download_file_permission_required,
    edit_issue_permission_required,
    permission_required,
    resolve_issue_permission_required,
    restore_issue_permission_required,
)
from issueless.issue import bp
from issueless.issue.helpers import (
    admin_reviewer_add_notification,
    assign_validation,
    comment_validation,
    create_presigned_url,
    create_validation,
    delete_file_in_s3,
    delete_issue_files_in_s3,
    edit_validation,
    sizeof_fmt,
    upload_file_to_s3,
)
from issueless.models import db, Comment, File, Issue, Permission, UserProject


@bp.route('/<int:issue_id>')
@login_required
@access_issue_permission_required
def issue(user_project, issue):
    """Renders the issue page."""
    return render_template(
        'issue.html',
        title=issue.title,
        user_project=user_project,
        issue=issue,
        files=issue.files.order_by(File.timestamp),
        comments=issue.comments.order_by(Comment.timestamp.desc()),
        member_user_projects=user_project.project.user_projects.order_by(
            UserProject.timestamp
        ),
    )


@bp.route('/create', methods=['POST'])
@login_required
@permission_required(Permission.READ_PROJECT)
def create(user_project):
    """Creates a new issue.

    Args:
        user_project:
            in: permission_required() decorator
            type: UserProject
            description: A UserProject object whose user_id belongs to the current user
            and project_id is the same as the query parameter - id.
        title：
            in: formData
            type: string
            description: The new issue's title.
        description：
            in: formData
            type: string
            description: The new issue's description.

    Responses:
        302:
            description: Redirect to project page.
        403:
            description: Forbidden.
        404:
            description: Project not found.
    """

    title = request.form.get('title')
    description = request.form.get('description')

    project = user_project.project
    error = create_validation(title, description)
    if error is not None:
        flash(error)
    else:
        new_issue = Issue(
            title=title, description=description, creator=current_user, project=project,
        )
        db.session.add(new_issue)
        admin_reviewer_add_notification(
            project,
            'new issue',
            {
                'avatar': current_user.avatar(),
                'fullname': current_user.fullname(),
                'projectTitle': project.title,
                'issueTitle': title,
            },
        )
        db.session.commit()

    return redirect(url_for('project.project', id=project.id))


@bp.route('/<int:issue_id>/edit', methods=['POST'])
@login_required
@edit_issue_permission_required
def edit(project, issue):
    """Edits an issue.

    Edits an issue's title and description. If the project's status is In Progress,
    edits the priority and assignee too.

    Produces:
        application/json
        text/html

    Args:
        project:
            in: edit_issue_permission_required() decorator
            type: Project
            description: A Project object whose id is the same as the id in the path.
        issue:
            in: edit_issue_permission_required() decorator
            type: Issue
            description: An Issue object whose id is the same as the id in the path.
        title:
            in: json
            type: string
            description: The issue's new title.
        description:
            in: json
            type: string
            description: The issue's new description.
        priority:
            in: json
            type: String
            description: The priority level of the issue.
        assignee_id:
            in: json
            type: String
            description: The assignee's id.


    Responses:
        200:
            description: Edit successfully.
        400:
            description: Bad request.
        403:
            description: Forbidden.
        404:
            description: Project or issue does not exist.
        422:
            description: Unprocessable.
    """

    body = request.get_json()
    title = body.get('title')
    description = body.get('description')
    if None in (title, description):
        abort(400)

    if issue.status == 'In Progress':
        priority = body.get('priority')
        assignee_id = body.get('assignee_id')
        if None in (priority, assignee_id):
            abort(400)

        new_assignee = edit_validation(
            issue, title, description, project, priority, assignee_id
        )
        issue.priority = priority
        if issue.assignee != new_assignee:
            if issue.assignee != current_user:
                issue.assignee.add_notification(
                    'remove assignee',
                    {
                        'avatar': current_user.avatar(),
                        'fullname': current_user.fullname(),
                        'issueTitle': issue.title,
                    },
                )
            if new_assignee != current_user:
                new_assignee.add_notification(
                    'assign issue',
                    {
                        'avatar': current_user.avatar(),
                        'fullname': current_user.fullname(),
                        'projectId': project.id,
                    },
                    issue.id,
                )
            issue.assignee_id = assignee_id
    else:
        edit_validation(issue, title, description)

    issue.title = title
    issue.description = description
    db.session.commit()

    return {'success': True}


@bp.route('/<int:issue_id>/delete', methods=['POST'])
@login_required
@delete_issue_permission_required
def delete(project, issue):
    """Deletes an issue.

    Produces:
        application/json
        text/html

    Args:
        project:
            in: delete_issue_permission_required() decorator
            type: Project
            description: A Project object whose id is the same as the id in the path.
        issue:
            in: delete_issue_permission_required() decorator
            type: Issue
            description: An Issue object whose id is the same as the id in the path.

    Responses:
        302:
            description: Redirect to project page.
        400:
            description: Bad request.
        403:
            description: Forbidden.
        404:
            description: Project or issue does not exist.
    """

    data = {
        'avatar': current_user.avatar(),
        'fullname': current_user.fullname(),
        'projectTitle': project.title,
        'issueTitle': issue.title,
    }
    if issue.creator != current_user:
        issue.creator.add_notification(
            'delete issue', data,
        )
    if issue.assignee is not None and issue.assignee != current_user:
        issue.assignee.add_notification(
            'delete issue', data,
        )

    if issue.files.first() is not None:
        delete_issue_files_in_s3(str(issue.id))
    db.session.delete(issue)
    db.session.commit()

    return redirect(url_for('project.project', id=project.id))


@bp.route('/<int:issue_id>/assign', methods=['POST'])
@login_required
@assign_issue_permission_required
def assign(project, issue):
    """Assigns an issue.

    Args:
        project:
            in: assign_issue_permission_required() decorator
            type: Project
            description: A Project object whose id is the same as the id in the path.
        issue:
            in: assign_issue_permission_required() decorator
            type: Issue
            description: An Issue object whose id is the same as the id in the path.
        priority:
            in: formData
            type: String
            description: The priority level of the issue.
        assignee_id:
            in: formData
            type: int
            description: The assignee's id.

    Responses:
        302:
            description: Redirect to project page.
        400:
            description: Bad request.
        403:
            description: Current user does not have the permission.
        404:
            description: Project or issue does not exist.
    """

    priority = request.form.get('priority')
    assignee_id = request.form.get('assignee_id')

    error = assign_validation(project, issue, priority, assignee_id)

    if error is not None:
        flash(error)
    else:
        issue.priority = priority
        issue.status = 'In Progress'
        issue.assignee_id = assignee_id
        if issue.assignee != current_user:
            issue.assignee.add_notification(
                'assign issue',
                {
                    'avatar': current_user.avatar(),
                    'fullname': current_user.fullname(),
                    'projectId': project.id,
                },
                issue.id,
            )
        db.session.commit()

    return redirect(url_for('project.project', id=project.id))


@bp.route('/<int:issue_id>/restore', methods=['POST'])
@login_required
@restore_issue_permission_required
def restore(project, issue):
    """Restores a closed or resolved issue back to previous status.

    Restores a closed or resolved issue back to previous status. Restores resolved

issueless/project/__init__.py
from flask import Blueprint

bp = Blueprint('project', __name__, url_prefix='/projects')

from issueless.project import views

issueless/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons|Material+Icons+Outlined" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Gothic+A1" rel="stylesheet" />
  <link rel="stylesheet" href="{{ url_for('static', filename='packages/theme.css') }}" media="all" />
  <link href="https://fonts.googleapis.com/css2?family=Satisfy&display=swap" rel="stylesheet" />
  <script src="https://kit.fontawesome.com/f8c044b431.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" />
  <title>
    {% if title %} {{ title }} {% endif %}
  </title>
  {% block header %}{% endblock %}
</head>

<body>
  <div class="layout layout-nav-top">
    <div class="navbar navbar-expand bg-dark navbar-dark sticky-top py-0">
      <a class="navbar-brand" href="{{ url_for('index') }}"
        style="font-family: 'Satisfy', cursive; font-size: 2rem;">Issueless</a>
      <div class="d-flex align-items-center">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse"
          aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse justify-content-between" id="navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              <i id="notification-icon" class="material-icons">notifications</i>
            </a>
            <div class="dropdown-menu dropdown-menu-right notification-dropdown p-0"
              aria-labelledby="notificationDropdown">
              <div class="notification-content">
                <button class="btn btn-link" style="color: #6c757d;">
                  <u>View All</u>
                </button>
                <button class="btn btn-link float-right" style="color: #6c757d;">
                  <u>Mark All as Read</u>
                </button>
                <ul class="list-group list-group-flush notification-view-unread">
                  <li id="notification-no-unread" class="list-group-item py-5" hidden>
                    <h3 class="text-center">No Unread Notifications</h3>
                  </li>
                  <li id="notification-no-read-and-unread" class="list-group-item py-5" hidden>
                    <h3 class="text-center">No Notifications</h3>
                  </li>
                </ul>
              </div>
            </div>
          </li>
          <li class="nav-item mx-4">
            <a href="{{ url_for('auth.logout') }}" class="nav-link">
              <i class="fas fa-user-times"></i>
              Log Out
            </a>
          </li>
          <li class="nav-item">
            <img src="{{ current_user.avatar() }}" class="avatar" alt="Avatar" />
          </li>
        </ul>
      </div>
    </div>

    <div class="main-container">
      <div class="breadcrumb-bar navbar bg-white sticky-top">
        {% block breadcrumb %}{% endblock %}
      </div>

      {% with messages = get_flashed_messages() %}
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}

      <div class="container">
        <div class="row justify-content-center">
          <div class="col-xl-10 col-lg-11">
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
  </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
  </script>
  <script src="{{ url_for('static', filename='packages/autosize.min.js') }}"></script>
  <script src="{{ url_for('static', filename='packages/flatpickr.min.js') }}"></script>
  <script src="{{ url_for('static', filename='packages/prism.js') }}"></script>
  <script src="{{ url_for('static', filename='packages/draggable.bundle.legacy.js') }}"></script>
  <script src="{{ url_for('static', filename='packages/swap-animation.js') }}"></script>
  <script src="{{ url_for('static', filename='packages/dropzone.js') }}"></script>
  <script src="{{ url_for('static', filename='packages/list.min.js') }}"></script>
  <script src="{{ url_for('static', filename='packages/theme.js') }}"></script>
  <script src="{{ url_for('static', filename='packages/moment.js') }}"></script>

  <script src="{{ url_for('static', filename='js/base/helpers.js') }}"></script>
  <script src="{{ url_for('static', filename='js/base/base.js') }}"></script>
  <script src="{{ url_for('static', filename='js/base/notifications.js') }}"></script>
  {% block scripts %}{% endblock %}
</body>

</html>

issueless/templates/dashboard.html
{% extends 'base.html' %}
{% import 'macros.html' as macros %}

{% block breadcrumb %}
{{ macros.breadcrumb([('Dashboard', None)]) }}
{% endblock %}

{% block content %}
<div class="page-header mb-4">
  <div class="media">
    <img src="{{ current_user.avatar() }}" alt="Avatar" class="avatar avatar-lg mt-1" />
    <div class="media-body ml-3">
      <h1 class="mb-0">{{ current_user.fullname() }}</h1>
      <p class="lead">{{ current_user.username }}</p>
    </div>
  </div>
</div>

<ul class="nav nav-tabs nav-fill" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" data-toggle="tab" href="#projects" role="tab" aria-controls="projects"
      aria-selected="true">Projects</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#issues" role="tab" aria-controls="issues"
      aria-selected="false">Issues</a>
  </li>
</ul>

<div class="tab-content">
  <div class="tab-pane fade show active" id="projects" role="tabpanel" data-filter-list="content-list-body">
    <div class="content-list">
      <div class="row content-list-head">
        <div class="col-auto">
          <h3>Projects</h3>
          <button class="btn btn-round" data-toggle="modal" data-target="#project-create-modal">
            <i class="material-icons">add</i>
          </button>
        </div>
        <form class="col-md-auto">
          <div class="input-group input-group-round">
            <div class="input-group-prepend">
              <span class="input-group-text">
                <i class="material-icons">filter_list</i>
              </span>
            </div>
            <input type="text" id="project-filter-input" class="form-control filter-list-input"
              placeholder="Filter projects" aria-label="Filter Projects" />
          </div>
        </form>
      </div>

      <div id="project-list" class="content-list-body row">
        {% set progress_bar_color = ['bg-danger', 'bg-warning', 'bg-primary', 'bg-success', 'bg-info'] %}
        {% for user_project in user_projects%}
        {% set project = user_project.project %}
        {% set role = user_project.role.name %}
        {% set user_count = project.user_projects.count() %}

        {% set resolved_issues_count = project.issues.filter_by(status='Resolved').count() %}
        {% set total_issues_count = project.issues.filter_by(status='Open').count() + project.issues.filter_by(status='In Progress').count() + resolved_issues_count %}
        <div class="col-lg-6">
          <div class="card card-project">
            <div class="progress">
              {% if total_issues_count == 0 %}
              <div class="progress-bar {{ progress_bar_color[loop.index0 % 5] }}" role="progressbar" style="width: 0%;"
                aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">
              </div>
              {% else %}
              {% set percentage = resolved_issues_count / total_issues_count * 100 %}
              <div class="progress-bar {{ progress_bar_color[loop.index0 % 5] }}" role="progressbar"
                style="width: {{ percentage }}%;" aria-valuenow="{{ percentage}}" aria-valuemin="0" aria-valuemax="100">
              </div>
              {% endif %}
            </div>
            <div class="card-body">
              <div class="dropdown card-options">
                <button class="btn-options" type="button" id="project-dropdown-button-{{ loop.index }}"
                  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">more_vert</i>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                  {% if role == 'Admin' %}
                  <a class="dropdown-item" href="#" data-toggle="modal" data-target="#project-edit-modal"
                    data-action="{{ url_for('project.edit', id=project.id) }}" data-original-title="{{ project.title }}"
                    data-original-description="{{ project.description }}">Edit</a>
                  <div class="dropdown-divider"></div>
                  <form action="{{ url_for('project.delete', id=project.id) }}" method="POST">
                    <button type="submit" class="dropdown-item btn-link text-danger">
                      Delete Project
                    </button>
                  </form>
                  {% else %}
                  <form action="{{ url_for('project.quit', id=project.id) }}" method="POST">
                    <button type="submit" class="dropdown-item btn-link text-danger">
                      Leave Project
                    </button>
                  </form>
                  {% endif %}
                </div>
              </div>
              <div class="card-title">
                <a href="{{ url_for('project.project', id=project.id) }}">
                  <h5 id="project-title-{{ loop.index }}" class="text-truncate" data-filter-by="text">
                    {{ project.title }}
                  </h5>
                </a>
              </div>
              <ul class="avatars">
                {% for user_project_2 in project_users[loop.index0].limit(10) %}
                {% set user = user_project_2.user %}
                <li>
                  <img src="{{ user.avatar() }}" alt="{{ user.fullname() }}" class="avatar" data-toggle="tooltip"
                    data-placement="top" title="{{ user.first_name }}" />
                </li>
                {% endfor %}
                {% if user_count >= 10 %}
                <li>
                  <div id="member-count" class="avatar text-dark text-center border-0"
                    style="background: #dee2e6; padding-top: 3px;" data-toggle="tooltip" data-placement="top"
                    title="{{ user_count - 10 }} more members">
                    +{{ user_count - 10 }}
                  </div>
                </li>
                {% endif %}
              </ul>

              <div class="card-meta d-flex justify-content-between">
                <div class="d-flex align-items-center">
                  <i class="material-icons mr-1">playlist_add_check</i>
                  <span class="text-small">{{ resolved_issues_count }}/{{ total_issues_count }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <div class="tab-pane fade" id="issues" role="tabpanel">
    <div class="row content-list-head">
      <div class="col-auto">
        <h3>Issues</h3>
      </div>
    </div>

    <div class="content-list-body">
      <div class="card-list" data-filter-list="card-assigned-list-body">
        <div class="card-list-head pb-2">
          <h5 class="my-auto">Assigned to me</h5>
          <form class="ml-auto mr-3">
            <div class="input-group input-group-round">
              <div class="input-group-prepend">
                <span class="input-group-text">
                  <i class="material-icons">filter_list</i>
                </span>
              </div>
              <input type="text" class="form-control filter-list-input" placeholder="Filter issues"
                aria-label="Filter Issues" />
            </div>
          </form>
        </div>
        <div class="card-assigned-list-body">
          {% for issue in assigned_issues %}
          <div class="card card-issue">
            <div class="card-body">
              <div class="card-title text-truncate">
                <a href="{{ url_for('issue.issue', id=issue.project.id, issue_id=issue.id) }}">
                  <h6 class="text-truncate" data-filter-by="text">
                    {{ issue.title }}
                  </h6>
                </a>
                <span class="text-small" data-filter-by="text">
                  {{ issue.project.title }}
                </span>
              </div>
              <div class="card-meta mr-3">
                <span>
                  Priority: <strong data-filter-by="text">{{ issue.priority }}
                    {% if issue.priority == 'High' %}&#x1F525;{% endif %}</strong>
                </span>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

      <div class="card-list" data-filter-list="card-review-list-body">
        <div class="card-list-head pb-2">
          <h5 class="my-auto">Waiting for Review</h5>
          <form class="ml-auto mr-3">
            <div class="input-group input-group-round">
              <div class="input-group-prepend">
                <span class="input-group-text">
                  <i class="material-icons">filter_list</i>
                </span>
              </div>
              <input type="text" class="form-control filter-list-input" placeholder="Filter issues"
                aria-label="Filter Issues" />
            </div>
          </form>
        </div>
        <div class="card-review-list-body">
          {% for issue in missing_review_issues %}
          <div class="card card-issue">
            <div class="card-body">
              <div class="card-title text-truncate">
                <a href="{{ url_for('issue.issue', id=issue.project.id, issue_id=issue.id) }}">
                  <h6 class="text-truncate" data-filter-by="text">
                    {{ issue.title }}
                  </h6>
                </a>
                <span class="text-small" data-filter-by="text">
                  {{ issue.project.title }}
                </span>
              </div>
              <div class="card-meta mr-3">
                <span>
                  Priority: <strong data-filter-by="text">{{ issue.priority }}
                    {% if issue.priority == 'High' %}&#x1F525;{% endif %}</strong>
                </span>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>

<form class="modal fade" id="project-create-modal" tabindex="-1" aria-hidden="true"
  action="{{ url_for('project.create') }}" method="POST">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">New Project</h5>
        <button type="button" class="close btn btn-round" data-dismiss="modal" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
      </div>
      <div class="modal-body">
        {% if user_projects.count() >= 8 %}
        <div id="project-create-alert" class="alert alert-warning" role="alert">
          You can only have 8 or less projects. Please leave one existing
          project before you add any more.
        </div>
        {% endif %}
        <h6>Project Details</h6>
        <div class="form-group row align-items-center">
          <label class="col-3">Title</label>
          {% if user_projects.count() >= 8 %}
          <input class="form-control col" type="text" placeholder="Project title" name="title" maxlength="80"
            disabled />
          {% else %}
          <input class="form-control col" type="text" placeholder="Project title" name="title" maxlength="80" />
          {% endif %}
        </div>
        <div class="form-group row">
          <label class="col-3">Description</label>
          {% if user_projects.count() >= 8 %}
          <textarea class="form-control col" maxlength="200" rows="3" placeholder="Project description"
            name="description" disabled></textarea>
          {% else %}
          <textarea class="form-control col" maxlength="200" rows="3" placeholder="Project description"
            name="description"></textarea>
          {% endif %}
        </div>
      </div>
      <div class="modal-footer">
        <button role="button" class="btn btn-primary" type="submit" disabled>
          Create Project
        </button>
      </div>
    </div>
  </div>
</form>

<form class="modal fade" id="project-edit-modal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Project</h5>
        <button type="button" class="close btn btn-round" data-dismiss="modal" aria-label="Close">
          <i class="material-icons">close</i>
        </button>
      </div>
      <div class="modal-body">
        <h6>Project Details</h6>
        <div class="form-group row align-items-center">
          <label class="col-3">Title</label>
          <input class="form-control col" type="text" placeholder="Project title" maxlength="80" />
        </div>
        <div class="form-group row">
          <label class="col-3">Description</label>
          <textarea class="form-control col" maxlength="200" rows="3" placeholder="Project description"></textarea>
        </div>
      </div>
      <div class="modal-footer">
        <button role="button" class="btn btn-primary" type="submit" disabled>
          Save
        </button>
      </div>
    </div>
  </div>
</form>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/dashboard/dashboard.js') }}"></script>
<script src="{{ url_for('static', filename='js/dashboard/edit_project.js') }}"></script>
{% endblock %}

issueless/templates/macros.html
{% macro breadcrumb(items) %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    {% for item, link in items %} {% if link == None %}
    <li class="breadcrumb-item active" aria-current="page">{{ item }}</li>
    {% else %}
    <li class="breadcrumb-item"><a href="{{ link }}">{{ item }}</a></li>
    {% endif %} {% endfor %}
  </ol>
</nav>
{% endmacro %}